# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Welcome to my website
email: your-email@domain.com
description: > You can find me on IRC on freenode, usually in the arch linux channels, find me @hunedd
I do not check emails frequently, but I will usually check it every once in a while, usually once every 3 days.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: not yet!
github_username:  hunedd

# Build settings
markdown: kramdown
